import type {Metadata} from 'next'
import {Inter, Montserrat} from 'next/font/google'
import '@/core/style/globals.css'
import Header from './components/Header'
import Quote from './components/Quote'
import Newsletter from './components/Newsletter'
import Footer from './components/Footer'

const inter = Montserrat({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<main className='py-16 flex flex-col items-center'>
					{children}

					<Quote />
					<Newsletter />
					<Footer />
				</main>
			</body>
		</html>
	)
}
